### ISSUE TITLE
Python API Providing Enable Password at Prompt not Working

### ISSUE THREAD

**Issue by bssybeep** [knipknap/exscript#100]
This code is looping through a list of IP addresses and SSH to each hop.  One of the hops is prompting for an enable password.  The Exscript code is not passing down the provided password.

for ips in newlist:  
    account = Account(name = user_name, password = pswd, password2 = 'enable_password')
    host = Host('ssh://{}'.format(ips))
    host.set_account(account)
    start(account, host, port_debug)

**Comment by egroeper** [comment]
Which driver are you using?
Could you try with `start(account, host, port_debug, verbose=2)`?

**Comment by bssybeep** [comment]
Thanks for the reply.

I just tried the following, which didn't work:

for ips in newlist:
    account = Account(name = user_name, password = pswd, password2 =
'mypassword')
    host = Host('ssh://{}'.format(ips))
    host.set_account(account)
    start(account, host, port_debug, verbose=2)


when the script gets to the device asking for an enable password, it
displays this and eventually times out:

SJC20-A5-GW1>enable

Password:

thanks,

Jeff

**Comment by egroeper** [comment]
Unfortunately this doesn't answer my question what device this is about / what driver you are using.
I thought this would get written in front of each line, but I could be wrong.

**Comment by bssybeep** [comment]
Thanks for the reply.  If I understand your question correctly,
The device is a Cisco switch running IOS.

thanks

**Comment by egroeper** [comment]
Now I know which device you want to connect to (and which driver should be in use), but unfortunately I currently still can't tell what's going wrong.

Could you try the problematic device with this and send me the output (with XXXed passwords, if there are any in)? You should remove/change any sensitive information, but the less you change, the better are my chances to realize what's going wrong.

```
account = Account(name = user_name, password = pswd, password2 = 'enable_password')
conn = SSH2(debug = 2)
conn.connect('ssh://{}'.format(<ip of problematic device>))
conn.login(account)

conn.send('exit\r')
conn.close()
```

**Comment by knipknap** [comment]
Closing for lack of feedback
