### ISSUE TITLE
When using max_threads = 2.

### ISSUE THREAD

**Issue by braincrash** [knipknap/exscript#101]
Hi,

When using max_threads = 2, for example can I log the output to a file? I tried but I must be doing something wrong since I only receive a success from each host.

Thanks.

**Comment by braincrash** [comment]
If it is not to much trouble can you provide an example of:
log_to
log_to_file
In a queue script.

What I pretend is to log the output of multiple hosts by host:

host1
>something
>returns yes I'm host1
host2
>something
>returns yes I'm host2
...

Thanks

**Comment by egroeper** [comment]
As documented in [Queue.py](https://github.com/knipknap/exscript/blob/c58f68192e57fbdd8ced6c963f9b5bfe5ec5aec6/src/Exscript/Queue.py#L203) live conversation is only logged / printed with max_threads = 1. With max_threads >= 1 you wiill only get that success messages.
I think redirecting logging output to a file is not the right way to do, what you want.

Should should think about letting your script do more of the work.
With exscript you can run command and capture _and_ interpret the output.

Of course you could simply use ia global dict, concatenate the responses of all commands into a string and copy the string into the dict for each host:

```
from Exscript.util.start    import quickstart

responses = {}

def do_something(job, host, conn):
    responses[host.name] = ''
    conn.execute('command1')
    responses[host.name] += conn.response
    conn.execute('command2')
    responses[host.name] += conn.response


quickstart(('localhost', 'otherhost'), do_something)

for host in responses.keys():
    print host
    print responses[host] 
```
