### ISSUE TITLE
Having trouble with driver for Pirelli Routers

### ISSUE THREAD

**Issue by braincrash** [knipknap/exscript#103]
Hi,

I'm having trouble parsing the prompt for Pirelli routers.

TimeoutException: Buffer: '\r\n > '

I simple can get pass this, can anyone give some hits?

After trying the simples methods I went extreme :D 
_prompt_re   = [re.compile(r'\n.*>.*', re.MULTILINE|re.DOTALL|re.I)]

Thanks,
TC

**Comment by egroeper** [comment]
This simply means, that exscript doesn't know your device, yet. You need to write a driver to support it. A driver is mostly a collection of regexes working for your device (describing the CLI).

To have a starting point, you could look at the driver for ios:
https://github.com/knipknap/exscript/blob/master/src/Exscript/protocols/drivers/ios.py

If you want to write a driver, it is important, that you check os detection is still working with your driver:
```
cd tests/Exscript/protocols/
python OsGuesserTest.py
```

**Comment by braincrash** [comment]
I did, but the regex was not working!
I manage to put it working, can anyone explain the return 95 or return 20, on check header os:

    def check_head_for_os(self, string):
        if 'User Access Verification' in string:
            return 60
        if _tacacs_re.search(string):
            return 50
        if _user_re[0].search(string):
            return 30
        return 0

Thanks

**Comment by egroeper** [comment]
check_head_for_os is called during os detection and returns a score (between 0 and 100). The driver returning the highest score gets selected.
We have some banner files of the different devices in the test directory. The OsGuesser tries to guess the os using the check_head_for_os methods of the drivers. If for each banner file the correct driver gets selected, os guessing should work fine. Otherwise the test fails.

**Comment by egroeper** [comment]
You can think of the score as a probability. The driver returns the likelihood of being run on the correct device.

**Comment by braincrash** [comment]
Nice! Thank you for the explanation.

**Comment by egroeper** [comment]
If you have a working driver, I would happily accept a pull request.
