### ISSUE TITLE
Unpredictable output

### ISSUE THREAD

**Issue by mmernik** [knipknap/exscript#104]
Hi

I have a problem with this output (dynamic output ). I don't know how many {enter} do i need to complete the output.

--------------------------------- output ----------------------------
<p>
User-DSLAM-03#show ip igmp snooping table
 Igmp Joined Group member : 74

 Querier :
   Vlan: 10   Port: 49 Querier : 10.0.1.25 ExpireTime : 100

 IGMP Host :

 --------------- ------ ---- ---------------- --------------- -------- -------
   type(version)  Vlan  port   Group joined    Reporter-ip     expire   Index
 --------------- ------ ---- ---------------- --------------- -------- -------
  Dynamic(v2)       10     3  224.2.2.2         10.167.221.152    120   2
  Dynamic(v2)       10     7  224.2.2.2         10.167.220.79     120   3
  Dynamic(v2)       10     7  224.2.2.2         10.167.240.125    110   4
  Dynamic(v2)       10     9  224.2.2.2         10.167.219.24     110   5
  Dynamic(v2)       10     9  224.2.2.2         10.167.248.41     120   6
  Dynamic(v2)       10    10  224.2.2.2         10.167.233.8      120   7
  Dynamic(v2)       10    10  224.2.2.2         10.167.240.220    120   8
  Dynamic(v2)       10    12  224.2.2.2         10.167.245.71     120   9
  Dynamic(v2)       10    12  224.2.2.2         10.167.245.245    120   10
  Dynamic(v2)       10    13  224.2.2.2         10.167.247.176    120   11
  Dynamic(v2)       10    14  224.2.2.2         10.167.221.187    120   12
  Dynamic(v2)       10    15  224.2.2.2         10.167.201.1      110   13
  Dynamic(v2)       10    15  224.2.2.2         10.167.210.65     110   14
  Dynamic(v2)       10    15  224.2.2.2         10.167.240.240    110   15
--More--
<p>
------------------------------------------------------------------------------------------------------
SCRIPT:

        {connection.set_prompt(/(More)/)}
        show ip igmp snooping table
        {enter}

cya, Marko

**Comment by egroeper** [comment]
This is currently a problem with exscript, It doesn't support paging and I haven't found a way to do this right, yet.
The current solution / workaround is to disable paging in the device. This is often done in the driver.
You can have a look at ios.py method init_terminal:
https://github.com/knipknap/exscript/blob/master/src/Exscript/protocols/drivers/ios.py

**Comment by mmernik** [comment]
Thanks for response.

The problem is the device don't support paging :)

**Comment by braincrash** [comment]
Nice to see someone using this script in a IPTV environment :P 
If I'm not mistaken you can disable that --MORE-- "feature" on the DSLAM cli.

**Comment by mmernik** [comment]
Tiago Correia je 25.9.2015 ob 17:36 napisal:
>
> Nice to see someone using this script in a IPTV environment :P
> If I'm not mistaken you can disable that --MORE-- "feature" on the 
> DSLAM cli.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/knipknap/exscript/issues/104#issuecomment-143254095>.
>

Hello.
I use escript in all environments to pull data in real time from devices 
( CPE,BRAS,DSLAM, etc..)

This old DSLAM unfortunately, does not support the disable paging command.

-- 
lp, Marko Mernik

**Comment by braincrash** [comment]
humm if it supports IPTV it's not that old :P 
Thats really cool I also do that :)

We should talk :P

**Comment by mmernik** [comment]
Tiago Correia je 25.9.2015 ob 18:30 napisal:
>
> humm if it supports IPTV it's not that old :P
> Thats really cool I also do that :)
>
> We should talk :P
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/knipknap/exscript/issues/104#issuecomment-143269869>.
>
Ok we can. No problem.

**Comment by egroeper** [comment]
Sorry. I don't think, I can help you. exscript currently doesn't work, if paging is enabled and I abandoned my last try to implement support for paging. I currently can't remember the reason.

Feel free to try it yourself and submit a pull request.
