### ISSUE TITLE
Guest OS

### ISSUE THREAD

**Issue by braincrash** [knipknap/exscript#105]
Hi,

What would be the best way to detect the guest OS and then send the correct login credentials?

Thanks.

**Comment by egroeper** [comment]
It depends...
Looking at the other drivers, would be a good starting point.
Most drivers look at the SSH banner (text shown pre login) and the password prompt. Of course there has to be something to distinguish your device from other devices.

If you post the text/output of an example login, I could try to help you.

**Comment by braincrash** [comment]
I use telnet no SSH, but the principle must be the same I think...

I use this for the 3 routers I pretend to connect:

thomson/technicolor


_user_re     = [re.compile(r'sername : ', re.I)]
_password_re = [re.compile(r'assword : ', re.I)]
_prompt_re   = [re.compile(r'\{\w+\}\=\>', re.I)]

class ThomsonDriver(Driver):
    def __init__(self):
        Driver.__init__(self, 'thomson')
        self.user_re     = _user_re
        self.password_re = _password_re
        self.prompt_re   = _prompt_re

    def check_head_for_os(self, string):
        if _user_re[0].search(string):
            return 95
        return 0

    def init_terminal(self, conn):
        conn.execute(':env set var=COLUMNS value=200')

ADB/Pirelli 4000

_user_re     = [re.compile(r'Login: ', re.I)]
_password_re = [re.compile(r'Password: ', re.I)]
_prompt_re   = [re.compile(r'[\r\n]?.*\>.*', re.M|re.S|re.I)]

class ADBPirelli4000Driver(Driver):
    def __init__(self):
        Driver.__init__(self, 'ADBPirelli4000')
        self.user_re     = _user_re
        self.password_re = _password_re
        self.prompt_re   = _prompt_re

    def check_head_for_os(self, string):
        if _user_re[0].search(string):
            return 95
        return 0

ADB/Pirelli 1000

_user_re     = [re.compile(r'User Name : ', re.I)]
_password_re = [re.compile(r'User Password : ', re.I)]
_prompt_re   = [re.compile(r'(\w+) :\> ', re.M|re.S|re.I)]

class ADBPirelli1000Driver(Driver):
    def __init__(self):
        Driver.__init__(self, 'ADBPirelli1000')
        self.user_re     = _user_re
        self.password_re = _password_re
        self.prompt_re   = _prompt_re

    def check_head_for_os(self, string):
        if _user_re[0].search(string):
            return 70
        return 0

What I pretend is to identify the routers so I can send the correct credentials, since they are different.

Thanks.

**Comment by egroeper** [comment]
Writing drivers for exscript is about supporting devices, that aren't supported, yet. Exscript needs to know how prompts of a device (user, password, command line prompts) look like to support it.
If 2 devices work with the same driver, that would be perfectly fine.
For making automatic driver detection work, exscript additionally needs to know how to distinguish the device from others (especially in check_head_for_os).

You should know yourself (from a database?) which credentials to use at which device.

It would help a lot, if you could post the output / logs of a login to your devices. Please have a look at the existing banners:
https://github.com/knipknap/exscript/tree/master/tests/Exscript/protocols/banners

**Comment by braincrash** [comment]
Ok no prob here it is:

Thomson/Technicolor
```
Trying 127.0.0.1...
Connected to 127.0.0.1.
Escape character is '^]'.
Username : Administrator
Password : ********
------------------------------------------------------------------------

                             ______  Technicolor TG784n v3
                         ___/_____/\ 
                        /         /\\  10.2.1.D
                  _____/__       /  \\ 
                _/       /\_____/___ \  Copyright (c) 1999-2012, Technicolor
               //       /  \       /\ \
       _______//_______/    \     / _\/______ 
      /      / \       \    /    / /        /\
   __/      /   \       \  /    / /        / _\__ 
  / /      /     \_______\/    / /        / /   /\
 /_/______/___________________/ /________/ /___/  \ 
 \ \      \    ___________    \ \        \ \   \  /
  \_\      \  /          /\    \ \        \ \___\/
     \      \/          /  \    \ \        \  /
      \_____/          /    \    \ \________\/
           /__________/      \    \  /
           \   _____  \      /_____\/
            \ /    /\  \    /___\/
             /____/  \  \  /
             \    \  /___\/
              \____\/

------------------------------------------------------------------------
{Administrator}=>
```
ADB/Pirelli4000
```
Trying 127.0.0.1...

Connected to 127.0.0.1.

Escape character is '^]'.

BCM96328 Broadband Router
Login: admin
Password: 
 > 
 ```
 
 ADB/Pirelli1000
 ```
 Trying 127.0.0.1...

Connected to 127.0.0.1.

Escape character is '^]'.

User Name : admin
User Password : *****

 Telnet Manager Version 0.99.3_TR069_AnnexM


Type ? for Command-Sensitive Help, TAB match command

ROOT :> 
 ```

The login is always different in this three, I have the drivers created, they seemed ok because if I do a successful login it gives the correct router name.
But for that I need to know each credentials to use, in a lab environment all have the same user/pass.

Thanks.

**Comment by egroeper** [comment]
So you assign credentials based on device types? Do you know the ip and device type of each device? Exscript supports manually selecting the driver. That way you don't have to rely on os detection.

In most use cases you use the same credentials on every device you manage (i.e. the devices are configured to use Radius or something like that) or you know the credentials of each device (knowing the credentials based on the ip of the device).
Exscript has no method to bind account data based on the used driver.

**Comment by braincrash** [comment]
@egroeper I only know the IP.
If you use the same credentials on every device that a big security hole, this way I can assure that if a device gets compromise, only a fraction is affected.

Thanks

**Comment by egroeper** [comment]
Of course you could use different credentials based on the role a device has in your network. But I don't think the OS running on it is a useful criterion.
The more devices you have, the less it is feasible to make such things complex. You simply have other problems and need to implement other methods to make things secure.
