### ISSUE TITLE
OneOS & IOS driver overlaps

### ISSUE THREAD

**Issue by maximumG** [knipknap/exscript#108]
Hello,

From what I can see and what I was able to test on more than 6000 devices in my entreprise, The IOS driver is never chosen using auto-guessing. With _banner login_ and _banner motd_ set on IOS there is no way to check for IOS except for their "specific"prompt :

my-cisco-device#
my-cisco-device>

Unfortunately this prompt is also used by OneOS driver. So all devices are recognized as OneOS devices. This does indeed work for every interaction except for the Exception raised when bad commands are sent. The OneOS driver basically doesn't have any error regex that get raised on such case.

From what I can see OneOS and IOS prompt are 98% similar on an Exscript point of view except for the command line error regex and the _autoinit()_ method (IOS adds a _term with 0_ commands which is useless for nowadays up to date IOS).

Would it be possible to merge those two drivers, including :
- Add an error regex for IOS like devices
- Remove the _term width 0_ command sent via autoinit (not sure OneOS will support this)

I'll be glad to create a new merge request on this, if you all agree on this.

Thanks for your support and comments

**Comment by egroeper** [comment]
Since when is the "term width 0" command obsolete?

Feedback from someone using OneOS would be nice.

Unless someone comes with a reasonable veto on this, I would be happy to merge your pull request.

**Comment by maximumG** [comment]
Hello,

I worked on IOS version < 12 and had some issue getting the full output with Exscript when command *term width 0* was not set.
However with IOS version > 12 I never include *term width 0* command and I never had any issues.
Furthermore NXOS doesn't support the previous command anymore.

I will work on this merge request this week and will keep the OneOS driver which will handle OneOS, IOS and NXOS driver.

**Comment by knipknap** [comment]
I am pretty sure we originally started out with just one driver for both
operating systems, so I'd be very careful with this change. I believe
issues with the terminal initialization method ("term len 0"?) where the
reason.

This is also an API breaking change, we frequently match on the return
value of Transport.guess_os(). If the choice is between breaking either the
IOS or the OneOS driver... I'd keep the IOS one stable, since it's more
widely used.

That said, it's not my choice to make, I am glad you are rocking this
project.

-Samuel

**Comment by maximumG** [comment]
Thanks for your response @knipknap. The root cause of this change is that there is an inevitable overlap between OneOS and IOS. 
When both *banner login* and *banner motd* are set on an IOS device, the *guess_os* of Exscript won't choose IOS but rather OneOS as it matches a prompt like ".*[#>]$". 
This implies that error detection doesn't work as OneOS driver doesn't have any regex matching an error in the CLI).

I will still create a merge request to merge those two driver, but you may want to wait for a feedback from OneOS guy to see if that meets their needs too.

Just a quick and big thanks to this project as it is the underlying brick of an internal library I'm working as part of my job; aiming at being a standard interface between CLI from network devices and any python script (run using Ansible project).

**Comment by egroeper** [comment]
@maximumG 
> However with IOS version > 12 I never include term width 0 command and I never had any issues.

Do I understand this correctly, that every IOS release since ~2003 doesn't need this (IOS 12 was released somewhere around this? 11.2 support ended in 2002)

Unfortunately I don't know or use any Cisco devices.

**Comment by maximumG** [comment]
@egroeper : I don't say that removing term width 0 is an absolute law, only a Cisco representative could tell us more. 

However **from my own experience** where I'm dealing with more than 6000 Cisco devices including switches (2960 series, 3750 series, 3650 series,...), multi-layer switches (4500 series, 6500 series,...) and routers (1800 series, 2600 series,...), I never used the *term width 0* command since IOS 12 with Exscript and never had any issue parsing the output (as the autodiscover feature of Exscript choose the one_os driver only and not IOS in my case).

Hope this can help you in your decision :-)

**Comment by maximumG** [comment]
I found another way to better detect IOS instead of the misleading OneOS driver. When you run an SSH session you can find some clues about the remote OS using the SSH agent information. During SSH negotiation the remote agent version is sent by each SSH server, for IOS device it is sent as 'Cisco SSH 1.XX' (try to use SSH -vvvv and you will see the remote agent information appear)

It could be interesting to modify the OSGuesser to take into account this remote agent (contained in a attributes of the underlying Paramiko object).

Are you interested in such modification of code ?

**Comment by knipknap** [comment]
The OSguesser is protocol agnostic, and what you are suggesting would not work for Telnet. It may make sense for SSH, but you'd also have to redesign thr OsGuesserTest.

**Comment by knipknap** [comment]
I am closing this because it would include a design change and is not really a bug because Protocols.guess_os() is not guaranteed to work for every host.

However, if anyone wants to add support for letting OsGuesser take additional hints from the protocol adapter, feel free to re-open and provide a pull request.
