### ISSUE TITLE
function to add to device/router prompt

### ISSUE THREAD

**Issue by mathewfer** [knipknap/exscript#111]
Hi

Is there a function/method to get the device prompt?

Example. After connecting a Cisco router via telnet or ssh, we get the prompt like "router>" or <router#>. Currently, I can not see a way to get this prompt.

Thanks for letting me know how to get this  or add this to the code

Mathew

**Comment by iargue** [comment]
Hey Matthew,

Besides for getting device name, is there any other reason you need this data?

If you are looking for the hostname, just do "show run | i hostname" and it will return he hostname for you as the first line.

**Comment by knipknap** [comment]
Are you referring to the Python API, or to the template language? In case
of the former, check the return type of the execute() method (and similar
methods):


http://knipknap.github.io/exscript/api/Exscript.protocols.Protocol-class.html#execute

In case of the latter, I am sure there is a way, but I forgot which :-P

**Comment by egroeper** [comment]
@mathewfer I assume because of our really late answers you lost interest.
I will close this now. Feel free to add more info and I will reopen.
