### ISSUE TITLE
No Huawei support 

### ISSUE THREAD

**Issue by maxno1988** [knipknap/exscript#112]
Hi Dears. I'm trying to test out a simple script on a Huawei (AR2200) router to  get "display clock" info. But the script gets stuck after logging into the router by displaying login information and after 15 second gives an error: 
![error](https://cloud.githubusercontent.com/assets/16080405/11469192/dae98694-977e-11e5-864c-119b29e0d541.png)

PS: The script works with Unix machines. 
Has anyone tested it Exscript with Huawei routers/switches?

**Comment by nebi** [comment]
Don't know if you hade solved this yet but I have write my own drivers for Huawei 5300 and got that working. I am going to modify it a little bit more to support Huawei AR-serier(Should not take that much more time to get it working). When this is done I will make a pull request to the repo.

**Comment by egroeper** [comment]
Sorry. I recently had no time for this project. 
I would appreciate a pull request with your driver. You should have a look at #50, which contains a driver for Huawei, but had open issues with os detection.

**Comment by maximumG** [comment]
I was running under the same issue and modified the driver to match VRP software on Huawei. I will send a pull request ASAP.

**Comment by knipknap** [comment]
Thanks for the pull request #130, the change is now merged into master.
