### ISSUE TITLE
No support for mellanox devices

### ISSUE THREAD

**Issue by kpgx** [knipknap/exscript#116]
When connecting to a Mellanox device through SSH, exscript uses the generic driver and hangs on login. I've tried all other available drivers without success.

Does anyone have a working driver for Mellanox switches?

Kind regards,
Kasun Gamlath

**Comment by egroeper** [comment]
It's not that hard to write a driver yourself. But a user guide would be nice.

Since I don't have such a device, I can't write the driver.

**Comment by knipknap** [comment]
Since this is now more than one year old, I am closing the bug. If anyone can provide a driver, feel free to reopen.

For the record: Creating a driver is easy, best just look at

`src/Exscript/protocols/drivers/ios.py`

for an example.
