### ISSUE TITLE
Get result of executed template

### ISSUE THREAD

**Issue by renard** [knipknap/exscript#118]
Hi,

I am playing with templates:

```python
     Exscript.util.template.eval(conn, """
 {if os is "IOS"}
 show clock
 show ver
 {else}
 show system uptime | match Current
 {end}
 """, os="IOS", foo='bar')
     conn.waitfor(conn.get_prompt())
     print conn.response
```
This works but I on get the last result of the template (`show ver`)

On the other hand I run a static script which works fine:

```python
     for l in script:
         conn.response = None
         conn.execute(l)
         conn.waitfor(conn.get_prompt())
         print conn.response
```

Is there a way to convert a template to a static script?

**Comment by egroeper** [comment]
Sorry. This is an issue tracker. Please use it for bug reports only.
Your questions would better fit our mailing list or stackoverflow. 
To be honest, it seems like I missed some stackoverflow questions regarding exscript. But I just now tried to create a tag for exscript, which I then could follow.
To be sure, you could send a reminder to the mailing list, if your question doesn't get a reaction in a reasonable amount of time.

I will answer by email.
