### ISSUE TITLE
Python Unable to change user password for JunOS

### ISSUE THREAD

**Issue by dihego** [knipknap/exscript#119]
I need assistance with this project and issues im having.

I am able to make changes to this juniper router with no issues.. The issue comes in when I need to change the password for a user. 

Per the screen or the output below...
I have attempted:
user sends the command to change the password. Then it's suppose to get prompted with the New Password from the CLI which I'm attempting to enter it with the passwd1 and 2 string to be sent over per below. I even attempted to hid the output with getpass() but nothing.. it idles then since is unable to enter the password then it gets  skipped and goes to the expect:

`def JunOS(self,host_ips,global_level,commands,commit):

try:
			conn = SSH2(verify_fingerprint = False)
			conn.connect(host_ips)
			print "Connecting to : ", host_ips
			conn.login(account)
			conn.execute(global_level)
			print conn.response
			print 
			p1 =getpass.getpass()
			p2 =getpass.getpass()
			print "****"
			conn.execute(commands)   #This is where i enter set system login user userXX auth plain
			conn.set_prompt('New Password:')
			conn.send(p1)
			conn.set_prompt('Retype new password:')
			conn.send(p1)
			print conn.response

			conn.execute(commit)
			print conn.response
			print
			print "********************************"
			print "Commit executed !"
			print "********************************"
				#conn.close()
except:
			print "IP for this device : ", host_ips
			print "Unable to connect or Username/password are not"`

**Comment by egroeper** [comment]
Answered on the mailing list.
