### ISSUE TITLE
Python 3

### ISSUE THREAD

**Issue by chikanna1** [knipknap/exscript#120]
Anyone have success in using the python3 branch? I am getting errors with executing commands and the expect prompt

**Comment by egroeper** [comment]
Sorry. No Python3 support, yet.

Closing as duplicate of #73.

**Comment by alexkross** [comment]
I use Python3 for basic protocol support, no exscripts. Full-fledged porting is possible but boring and error-prone if not tested properly. Sorry, but have no spare time to complete.
Pull from my repo https://github.com/alexkross/exscript.git
