### ISSUE TITLE
SSH to IOS enable fails on high latency destinations

### ISSUE THREAD

**Issue by swinkl3** [knipknap/exscript#127]
Hi,

I have a large network with devices around the world. All devices are Cisco IOS. I am finding that when attempting to log in to devices with high latency the "ios: Expecting a prompt" predictably fails every second attempt and the script ends with TimeoutException. Ie. the first attempt logs in perfectly and I am able to run commands that I want, get output etc. If I fire off another attempt to the same device it will fail. If I go again it will work, then again, fail, then again, work etc etc. I am able to reproduce this on a number of different devices. 

I am running python 2.7.6 and exscript v2.1.507-gc052a59. Below is the code I am using. 
# !/usr/bin/python

import hashlib
import Exscript
import sys
import time

from Exscript.util.interact import read_login
from Exscript.protocols import SSH2
from Exscript import Account
from Exscript.protocols.drivers import ios

ip = str(sys.argv[1])
username = str(sys.argv[2])
password = str(sys.argv[3])
enable = str(sys.argv[4])

account = Account(username, password, enable)             # Prompt the user for his name and password
conn = SSH2(debug=5, verify_fingerprint = False)                       # We choose to use SSH2
conn.set_driver('ios')
conn.set_timeout(10)
conn.connect(ip)         # Open the SSH connection
conn.login(account, flush = True)                 # Authenticate on the remote host
conn.execute('terminal length 0')
conn.execute('show inv')
print conn.response
conn.send('exit\r')                 # Send the "exit" command
conn.close()

I have tried changing login to authenticate and auto_app_authorize with both flush = True but get the same problem. I have also to sleep the script at different points, but no dice.

Below is a debug=5 with paramiko debug on the same device both working and not working. I am not sure how to debug further than this, although it looks like the prompt is never captured properly, maybe because of a buffer/cache somewhere? Do I need to do anything else to cleanly close the session or something?

WORKING
root@ho-uc:~# python router-hardware.py _ipaddress_ _username_ _password_ _enable password_
DEBUG:paramiko.transport:starting thread (client mode): 0x5eacf0d0L
DEBUG:paramiko.transport:Local version/idstring: SSH-2.0-paramiko_2.0.2
DEBUG:paramiko.transport:Remote version/idstring: SSH-2.0-Cisco-1.25
INFO:paramiko.transport:Connected (version 2.0, client Cisco-1.25)
DEBUG:paramiko.transport:kex algos:[u'diffie-hellman-group-exchange-sha1', u'diffie-hellman-group14-sha1', u'diffie-hellman-group1-sha1'] server key:[u'ssh-rsa'] client encrypt:[u'aes128-cbc', u'3des-cbc', u'aes192-cbc', u'aes256-cbc'] server encrypt:[u'aes128-cbc', u'3des-cbc', u'aes192-cbc', u'aes256-cbc'] client mac:[u'hmac-sha1', u'hmac-sha1-96', u'hmac-md5', u'hmac-md5-96'] server mac:[u'hmac-sha1', u'hmac-sha1-96', u'hmac-md5', u'hmac-md5-96'] client compress:[u'none'] server compress:[u'none'] client lang:[u''] server lang:[u''] kex follows?False
DEBUG:paramiko.transport:Kex agreed: diffie-hellman-group1-sha1
DEBUG:paramiko.transport:Cipher agreed: aes128-cbc
DEBUG:paramiko.transport:MAC agreed: hmac-md5
DEBUG:paramiko.transport:Compression agreed: none
DEBUG:paramiko.transport:kex engine KexGroup1 specified hash_algo <built-in function openssl_sha1>
DEBUG:paramiko.transport:Switch to new keys ...
ios: Rejecting ssh-rsa host key for _ipaddress_: 1499f8577d91d1ce2b1067d32056f7b1
ios: Attempting to authenticate _username_.
ios: Authenticating with _paramiko_auth_password
DEBUG:paramiko.transport:userauth is OK
INFO:paramiko.transport:Authentication (password) successful!
DEBUG:paramiko.transport:[chan 0] Max packet in: 32768 bytes
DEBUG:paramiko.transport:[chan 0] Max packet out: 4096 bytes
DEBUG:paramiko.transport:Secsh channel 0 opened.
DEBUG:paramiko.transport:[chan 0] Sesch channel 0 request ok
DEBUG:paramiko.transport:[chan 0] Sesch channel 0 request ok
ios: Attempting to app-authenticate _username_.
ios: waiting for: ['[\r\n][^\r\n]_(?:bad secrets|denied|invalid|too short|incorrect|connection timed out|failed|failure)', 'user ?name: ?$', '(?:s\/key|otp-md4) (\d+) (\S+)', '(?:[\r\n]Password: ?|last resort password:)$', '[\r\n][\-\w+\.:/]+(?:\([^\)]+\))?[>#] ?$']
ios: Expecting a prompt
ios: Expected pattern: <generator object <genexpr> at 0x7f265e052140>
ios: Shell prompt received.
ios: Expecting a prompt
ios: Expected pattern: <generator object <genexpr> at 0x7f265e052140>
ios: Checking '\r\nADE-GW-VG-SRST>' for errors
ios: Calling driver.auto_authorize().
ios: Sending 'enable\r'
ios: Attempting to app-authorize *username_.
ios: waiting for: ['[\r\n][^\r\n]_(?:bad secrets|denied|invalid|too short|incorrect|connection timed out|failed|failure)', 'user ?name: ?$', '(?:s\/key|otp-md4) (\d+) (\S+)', '(?:[\r\n]Password: ?|last resort password:)$', '[\r\n][\-\w+\.:/]+(?:\([^\)]+\))?[>#] ?$']
ios: Expecting a prompt
ios: Expected pattern: <generator object <genexpr> at 0x7f265e052140>
ios: Cleartext password prompt received.
ios: Expecting a prompt
ios: Expected pattern: <generator object <genexpr> at 0x7f265e052140>
ios: Sending '_enable password_\r'
ios: waiting for: ['[\r\n][^\r\n]_(?:bad secrets|denied|invalid|too short|incorrect|connection timed out|failed|failure)', 'user ?name: ?$', '(?:s\/key|otp-md4) (\d+) (\S+)', '(?:[\r\n]Password: ?|last resort password:)$', '[\r\n][\-\w+\.:/]+(?:\([^\)]+\))?[>#] ?$']
ios: Expecting a prompt
ios: Expected pattern: <generator object <genexpr> at 0x7f265e052140>
ios: Shell prompt received.
ios: Expecting a prompt
ios: Expected pattern: <generator object <genexpr> at 0x7f265e052140>
ios: Checking '\r\nADE-GW-VG-SRST#' for errors
ios: Sending 'show inv\r'
ios: Expecting a prompt
ios: Expected pattern: <generator object <genexpr> at 0x7f265e052140>
ios: Checking 'show inv\r\n_REMOVEDFORBREVITY_' for errors
show inv
_REMOVEDFORBREVITY_
ADE-GW-VG-SRST#
ios: Sending 'exit\r'
DEBUG:paramiko.transport:[chan 0] EOF sent (0)
DEBUG:paramiko.transport:EOF in transport thread
root@ho-uc:~#

NOT WORKING
root@ho-uc:~# python router-hardware.py _ipaddress_ _username_ _password_ _enable password_
DEBUG:paramiko.transport:starting thread (client mode): 0xc7d010d0L
DEBUG:paramiko.transport:Local version/idstring: SSH-2.0-paramiko_2.0.2
DEBUG:paramiko.transport:Remote version/idstring: SSH-2.0-Cisco-1.25
INFO:paramiko.transport:Connected (version 2.0, client Cisco-1.25)
DEBUG:paramiko.transport:kex algos:[u'diffie-hellman-group-exchange-sha1', u'diffie-hellman-group14-sha1', u'diffie-hellman-group1-sha1'] server key:[u'ssh-rsa'] client encrypt:[u'aes128-cbc', u'3des-cbc', u'aes192-cbc', u'aes256-cbc'] server encrypt:[u'aes128-cbc', u'3des-cbc', u'aes192-cbc', u'aes256-cbc'] client mac:[u'hmac-sha1', u'hmac-sha1-96', u'hmac-md5', u'hmac-md5-96'] server mac:[u'hmac-sha1', u'hmac-sha1-96', u'hmac-md5', u'hmac-md5-96'] client compress:[u'none'] server compress:[u'none'] client lang:[u''] server lang:[u''] kex follows?False
DEBUG:paramiko.transport:Kex agreed: diffie-hellman-group1-sha1
DEBUG:paramiko.transport:Cipher agreed: aes128-cbc
DEBUG:paramiko.transport:MAC agreed: hmac-md5
DEBUG:paramiko.transport:Compression agreed: none
DEBUG:paramiko.transport:kex engine KexGroup1 specified hash_algo <built-in function openssl_sha1>
DEBUG:paramiko.transport:Switch to new keys ...
ios: Rejecting ssh-rsa host key for _ipaddress_: 1499f8577d91d1ce2b1067d32056f7b1
ios: Attempting to authenticate _username_.
ios: Authenticating with _paramiko_auth_password
DEBUG:paramiko.transport:userauth is OK
INFO:paramiko.transport:Authentication (password) successful!
DEBUG:paramiko.transport:[chan 0] Max packet in: 32768 bytes
DEBUG:paramiko.transport:[chan 0] Max packet out: 4096 bytes
DEBUG:paramiko.transport:Secsh channel 0 opened.
DEBUG:paramiko.transport:[chan 0] Sesch channel 0 request ok
DEBUG:paramiko.transport:[chan 0] Sesch channel 0 request ok
ios: Attempting to app-authenticate _username_.
ios: waiting for: ['[\r\n][^\r\n]*(?:bad secrets|denied|invalid|too short|incorrect|connection timed out|failed|failure)', 'user ?name: ?$', '(?:s\/key|otp-md4) (\d+) (\S+)', '(?:[\r\n]Password: ?|last resort password:)$', '[\r\n][\-\w+\.:/]+(?:\([^\)]+\))?[>#] ?$']
ios: Expecting a prompt
ios: Expected pattern: <generator object <genexpr> at 0x7f55c7284140>
Traceback (most recent call last):
  File "/var/www/myitv2/services/router-hardware.py", line 23, in <module>
    conn.login(account)                 # Authenticate on the remote host
  File "/usr/local/lib/python2.7/dist-packages/Exscript-v2.1.507_gc052a59-py2.7.egg/Exscript/protocols/Protocol.py", line 627, in login
    self.authenticate(account, flush = False)
  File "/usr/local/lib/python2.7/dist-packages/Exscript-v2.1.507_gc052a59-py2.7.egg/Exscript/protocols/Protocol.py", line 651, in authenticate
    self.app_authenticate(app_account, flush = flush)
  File "/usr/local/lib/python2.7/dist-packages/Exscript-v2.1.507_gc052a59-py2.7.egg/Exscript/protocols/Protocol.py", line 819, in app_authenticate
    self._app_authenticate(account, password, flush, bailout)
  File "/usr/local/lib/python2.7/dist-packages/Exscript-v2.1.507_gc052a59-py2.7.egg/Exscript/protocols/Protocol.py", line 723, in _app_authenticate
    raise TimeoutException(msg)
Exscript.protocols.Exception.TimeoutException: Buffer: ''
DEBUG:paramiko.transport:EOF in transport thread

Any help would be much appreciated, cheers.

**Comment by knipknap** [comment]
The second traceback just looks like the device is not actually sending anything after being connected (the incoming buffer is empty). So the prompt pattern can never match. I'm afraid there is little to see or debug at that point, besides possibly using "strace -f" to try and find out what is going in and out of the Python process.

**Comment by knipknap** [comment]
Feel free to reopen if `strace -f` yields any new results.
