### ISSUE TITLE
consume parameter not working in execute method

### ISSUE THREAD

**Issue by maximumG** [knipknap/exscript#131]
The method below is buggy when setting the *consume* parameter to **False**.

```python
execute("command_to_execute", consume=False)
```

Basically, I found that setting *consume* to **False** will call the inner SSH2 method *_domatch* with the *flush* parameter set to *False*.

```python
def _domatch(self, prompt, flush):
````

There is an issue with the *end* variable calculation on line 337 where it is set to the following statement. This means that the buffer is captured from the beginning until reaching the prompt (prompt excluded).

```python
end = self.buffer.size() - len(search_window) + match.start()
```

This should be changed to capture the whole buffer including the prompt, but only when the flush parameter is set to false on line 324

```python
            else:
                end = self.buffer.size()  # the end byte should be set to the size of the buffer
                self.response = self.buffer.head(end)
```

The second issue is that the buffer is not cleaned at all when the flush parameter is set to False. this implies that the execute needs to be called twice to get the right output. To avoid this, it is required to change the execute method in Protocol.py with the following line

```python
        if not consume:
            self.buffer.clear()
```

I will push a pull request concerning this issue ASAP.

Cheers.

**Comment by knipknap** [comment]
> This should be changed to capture the whole buffer including the prompt, but only when the flush parameter is set to false on line 324

I am not sure that I understand you correctly, this is inverted logic. The way it is intended, the buffer should be flushed when "consume" is True. It should flush up to the end of the matching regular expression.

> This should be changed to capture the whole buffer including the prompt, but only when the flush parameter is set to false on line 324

Again, it is intended the other way around. Set to True to flush the buffer up to the end of the matching Regex.

> The second issue is that the buffer is not cleaned at all when the flush parameter is set to False. this implies that the execute needs to be called twice to get the right output.

Why would that be the case? Do you have a simple test case that shows the problem?

**Comment by maximumG** [comment]
Thanks for your comment. Sorry if I was not clear. I will try to explain it better.

Basically I want to execute a command and retrieve the last prompt after the command output (in order to capture the prompt content).

When I use the execute command with the consume parameter set to False - meaning do **not** trim the prompt from the output - the prompt is still trim, due to the way the *_domatch* method is coded. I changed the code of the *_domatch* method in my last pull request.

Furthermore the *head* method on the buffer does not pop the buffer content. That is why the buffer is never cleared and you end with an uncleared buffer.

I was doing the test using the shell driver on a Unix machine with your last master branch. You can execute the command using your master branch and using the code of my pull request to check the differences if you want :-).

**Comment by knipknap** [comment]
> When I use the execute command with the consume parameter set to False - meaning do not trim the prompt from the output - the prompt is still trim, due to the way the _domatch method is coded. I changed the code of the _domatch method in my last pull request.

I can agree with that and with your change in SSH2.py

> Furthermore the head method on the buffer does not pop the buffer content. That is why the buffer is never cleared and you end with an uncleared buffer.

But that is intended. If flush is False, the buffer is supposed to remain unchanged.

**Comment by maximumG** [comment]
Thanks for your reply. 

I just understood the use of *consume* as you re explain it. I was wrong in thinking that consume only consider to not trim the prompt. So from what I understood, I can execute several commands with **consume=False** and get the full response once at the end of computation. Am I right ? 

Nevertheless would it be possible to modify your code on SSH2.py to include my change regarding our first statement ?

**Comment by knipknap** [comment]
Ok, I tested after only adding the following line from your pull request:

```
             else:
+                end = self.buffer.size()
                 self.response = self.buffer.head(end)

```
This causes the tests to fail however:

```
FAIL: testAppAuthorize (__main__.SSH2Test)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sam/tinker/projects/exscript/tests/Exscript/protocols/ProtocolTest.py", line 351, in testAppAuthorize
    self.failUnlessEqual(self.protocol.response, response)
AssertionError: 'password\n' != 'password\n\n127.0.0.1> '

======================================================================
FAIL: testAutoAppAuthorize (__main__.SSH2Test)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sam/tinker/projects/exscript/tests/Exscript/protocols/ProtocolTest.py", line 375, in testAutoAppAuthorize
    self.failUnlessEqual(self.protocol.response, response)
AssertionError: 'password\n' != 'password\n\n127.0.0.1> '

```

I can't see an error in the test, so I think something must be wrong with the changed buffer calculation.

**Comment by souperrod** [comment]
Is it that the test is wrong?  With @maximumG change, there's essentially no longer a buffer calculation, and the entire buffer is placed in self.response.  Without that, the prompt appears to always get stripped based on the calculation `end = self.buffer.size() - len(search_window) + match.start()`

In testAppAuthorize, prior to line 350 `self.doAppAuthorize(flush = True)`, there is no refresh of `response` from the previous tests that use `flush = False`.  Would it be necessary to repeat the initial `doProtocolAuthenticate` and `doProtocolAuthenticate` but with `flush = True` and update the contents of `response` prior to `self.doAppAuthorize(flush = True)`?

I haven't stepped all the way through the tests, but seems like if `flush` is being used to alter the data placed in `self.response` in `_domatch`, then the expectation is `self.protocol.response` should contain different data when calling `doAppAuthorize(flush = False)` vs `doAppAuthorize(flush = True)` yet still comparing to the same/previous stored value in `response`.

**Comment by knipknap** [comment]
@souperrod Your explanation is absolutely correct, and yes, doing it on a fresh VirtualDevice and connection makes sense.
I have added this in 0ecb5666dca743902743ef81785228ecc4e7fc64, but the tests still pass without the patch (and fail with it).

**Comment by knipknap** [comment]
I am closing this bug because we have no actual use case that fails; feel free to re-open if you have more info.

**Comment by maximumG** [comment]
@knipknap : The issue is still present. Are you still interested in this 'bug' fix ? I can try working on the *SSH2Test* test case and find out what is going wrong.

**Comment by knipknap** [comment]
Of course, if something is still wrong I'd be glad to know. We are using SSH in production and have no issues so far.

**Comment by maximumG** [comment]
In order to work in the right way I have the following question.

Do you have any functional use case in production where you need to gather the device's prompt after executing a command with the *execute* method ?

Do we agree that the *consume* parameter of the *execute* method could be use as a way to control whether the device's prompt should be trimed from the response output or not ?

> Your explanation is absolutely correct, and yes, doing it on a fresh VirtualDevice and connection makes sense.
I have added this in 0ecb566, but the tests still pass without the patch (and fail with it).

Do you have any clue about why the new test case do not pass ?

**Comment by knipknap** [comment]
I am not sure if we read the prompt after executing a command, but I am sure that we do read the response after executing a command. I am currently travelling on a vacation, so currently can not check in detail.

The consume parameter should have the semantic: If consume is False, don't change the buffer. Otherwise, remove everything from the buffer that was matched against the prompt regex.

The new test case does pass, but only before applying the above pull request. I currently don't understand why the pull request would make sense, that's why I think we need to add a test that demonstrates the problem first.

**Comment by maximumG** [comment]
> I am not sure if we read the prompt after executing a command, but I am sure that we do read the response after executing a command. I am currently travelling on a vacation, so currently can not check in detail.

I have some uses cases where I need to be able to read the final prompt in order to capture the 'hostname' after executing a command. Basically with the current implementation of the execute method, the final prompt is trimed from the response, no matter what the consume parameter is set to False or True.

> The consume parameter should have the semantic: If consume is False, don't change the buffer. Otherwise, remove everything from the buffer that was matched against the prompt regex.

From my use cases, the consume parameter is still removing the final prompt from the buffer even when consume is set to False so it is changing the buffer.

> I currently don't understand why the pull request would make sense

The pull request was to avoid triming the final prompt when consume is set to False.

Hope this could help to move forward on this issue
