### ISSUE TITLE
Install fails on Windows and probably on some Macs

### ISSUE THREAD

**Issue by flaurencin** [knipknap/exscript#133]
Hi,

I  needed a moment to figure it all, but it seems on none case sensitives file system we can't install properly.
The main reason in the exscript script is in the same directory than the Exscript source.

I tricked it by maming the script with .py in the end and changing the line 24 of setup.py
      scripts          = ['exscript.py'],

I think it would be better to have the script exscript inside the Exscript directory.
Then it make it available on windows and macs ;)

Thanks for you attention.

Kind regards,

**Comment by knipknap** [comment]
I can't think of a reason not to move it... could you send a pull request?

**Comment by flaurencin** [comment]
Hi,

PR #134 have been submitted.

Kind Regards,

**Comment by knipknap** [comment]
Fixed in #134

**Comment by flaurencin** [comment]
Thanks !
