### ISSUE TITLE
Change license to MIT

### ISSUE THREAD

**Issue by knipknap** [knipknap/exscript#135]
We are planning to release a large open source project that is built on top of Exscript. In order to avoid a mix of licenses that make it hard for everyone to use it, we would like to change the Exscript license from GPLv2 to the more liberal MIT license.

Generally accepted is the notion that everyone who wrote more than 7 lines of code needs to agree to the license change, hence this issue. I am writing to every contributor who added more than 7 lines of code.

@egroeper @mpenning @job @flaurencin @maximumG @cgill27 @pheller @magahet 

Can you please let me know if you agree to the license change?

**Comment by job** [comment]
I agree to changing the license to MIT.

Generally speaking I am in favor of liberal licenses.

Also I'd like to thank you, Samuel,  for your work on this project.

Job Snijders

**Comment by pheller** [comment]
I agree to the proposed change to an MIT license.

--phil

**Comment by egroeper** [comment]
I agree to changing the license to MIT.

**Comment by mpenning** [comment]
I agree to changing the license to MIT

**Comment by knipknap** [comment]
Thanks, everyone! This means that everyone who contributed more that 15 lines of code has signed off on the license change.

For the original assessment of contributions I simply looked at the GitHub contribution graph (https://github.com/knipknap/exscript/graphs/contributors). This is however not very accurate, so I reviewed the remaining contributors manually:

@flaurencin's contribution comes from recently moving a single file, which does not meet the minimum threshold for copyright.

@magahet added the Aruba driver, but it did not work at the time, so it was removed by Enno later.
The driver is also an exact copy of other drivers, except for 5 lines. So we do not need him to sign off on the license change.

@cgill27 later added a derived Aruba driver that contains only 2 additional LOC. So this also does not require signing off.

So that leaves us with maximumG's contribution, which comes from three commits:
- The first one adds one character to two lines.
- The second one adds the RIOS driver. This driver is, however, an exact copy of other drivers, except for 4 lines.
- The third fixes the Huawei driver by adding 6 lines and changing three: 6831d43fdd6112fb09926fe7520617d71cd63aae
He also did not add himself to the copyright header. In summary, I do not believe this constitutes the minimum threshold for copyright, but to be extra safe we may need to replace a few lines.

I'll wait a couple of days for more feedback before making the change.

**Comment by knipknap** [comment]
The Huawei driver patch actually contained a bug that made changing it necessary. I fixed it, so I think we're now save to change the license.

**Comment by maximumG** [comment]
Sorry for the delay but changing the licence is also fine for me.

**Comment by knipknap** [comment]
Great, Thanks, @maximumG!
