### ISSUE TITLE
Can not extract the files from the Exscript 2.2

### ISSUE THREAD

**Issue by 1001QAdotNET** [knipknap/exscript#136]
Are there any reasons why I can not extract the files from Exscript 2.2 ? Even when I use easy_install the process gets stuck at Logfile.py

This is on Windows 7 and Windows 10.

**Comment by knipknap** [comment]
I can't think of a reason why that may happen, the is nothing remarkable about that file. Is there anything like strace on Windows that might help you narrow it down?

**Comment by 1001QAdotNET** [comment]
Here is a picture of my attempt to extract the files with 7zip https://i.imgur.com/c5Q7r9q.png

When I try to install the package the error is saying the the file Logile.py could not be found (the exact path is a temp folder where the installer is supposed to unzip the files before installing them)

**Comment by knipknap** [comment]
Sorry, I don't have a Windows environment to reproduce this and on Linux the package installs fine. But this looks a lot like a problem with your environment rather than Exscript.

Since 7zip can't extract any file, perhaps there is a permission problem, or hard disk space shortage?

**Comment by 1001QAdotNET** [comment]
I tested this on two computers. I am going two ask two coworkers to extract the files today.

**Comment by 1001QAdotNET** [comment]
OK I have tested this on another computer (my colleague's computer) and it does the same
Apparently the existence of the file exscript in the root folder prevents the extractions of the other files int he archive because the folder Exscript can't be created! If I manually extract everything but the exscript file then everything is OK but the file exscript can not be added

**Comment by 1001QAdotNET** [comment]
This all comes down to this issue: in certain situations if you have a folder name and a file name sharing the same name there is a conflict and you get a message like this: **"there is already a folder with the same name as the file name you specified"** 

Is there any way to get around this from your point of view ?

**Comment by knipknap** [comment]
I just pushed a new release v2.3 that fixes the issue.

**Comment by 1001QAdotNET** [comment]
I am using the PyPi archive for getting my packages. Should I download it from there? If not how do I get and install the files from here Sorry for the noob question. I am working on Windows I have installed the VC9 compiler but I have no idea how to start make from there in order to install from the sources that I could get from here

C:\Windows\SysWOW64\cmd.exe /k ""C:\Users\MyNameHere\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\vcvarsall.bat" x86"

**Comment by 1001QAdotNET** [comment]
Ok I will try it in a minute
