### ISSUE TITLE
What is the way run Exscript via a bastion host that does not support Proxycommand?

### ISSUE THREAD

**Issue by 1001QAdotNET** [knipknap/exscript#137]
We have a bastion host and the access to all our network devices is done through this
The bastion runs on old SunOS version, doesn't seem to accept ProxyCommands

What is the best approach for working with this constrains ?
Is is possible to open the session with the bastion server using a generic driver and then open a session with the network device and then change the driver so I can interpret the output correctly ?

**Comment by knipknap** [comment]
Yes, the generic driver probably works with SunOS, and yes, you absolutely can switch the driver after opening the connection. Check out [Protocol.set_driver()](http://exscript.readthedocs.io/en/latest/Exscript.protocols.Protocol.html#Exscript.protocols.Protocol.Protocol.set_driver).
