### ISSUE TITLE
Is it OK if I ask support questions here ?

### ISSUE THREAD

**Issue by 1001QAdotNET** [knipknap/exscript#138]
I am learning this library and I could use some help in the process. Where is the best place to ask questions like how to do this or that or what is the meaning of a regular expression like this one used here: nxos: Expected pattern: ["'[\\\\r\\\\n][\\\\-\\\\w+\\\\.:/]+(?:\\\\([^\\\\)]+\\\\))?[>#] ?$'"]

**Comment by knipknap** [comment]
You can ask questions about Exscript here, but for general questions such as yours I'd recommend http://stackoverflow.com/ .

However, if you have no experience with regular expressions, I would recommend completing this tutorial first: https://regexone.com/

**Comment by 1001QAdotNET** [comment]
Thanks... Ijust posted my question here http://stackoverflow.com/questions/42905871/exscript-access-to-remote-network-devices-via-a-bastion-host-while-still-using

I will go over that tutorial although having to understand complex things like the above regex defeats the purpose of this very library which is suppose to hide complex thing for network engineers like me
