### ISSUE TITLE
Allied Telesis iMG

### ISSUE THREAD

**Issue by masontrep** [knipknap/exscript#144]
Trying to use this as concept to do mass update on 400+ Allied Telesis iMG devices.  Very simillar command structure to IOS.  Have been able to use for many things already.  Having an issues with the tftp copy operation though.  

It successfully starts the command and begins the copy operation, but after about 60 seconds it times out before the operation can complete.

is there a way to extend that timeout?

Here is what I run on the device normally.

iMG# copy tftp://10.15.132.12/AT-iMG2400-4.4.4 AT-iMG2400-4.4.4
Starting TFTP copy
Starting image flash write. This may take several minutes - please be patient (_After about 90 sec it completes_) Then back to prompt.
iMG#

Here is the error I get when I try to run the following:

exscript -l ~/ imgConfig.exscript ssh://10.15.130.67
enable
copy tftp://10.15.132.12/AT-iMG2400-4.4.4 AT-iMG2400-4.4.4
time.sleep(200.0) **Have tried this and also {connection.set_prompt()}**
end
wr

Any thoughts or Ideas on what I am missing.

Thanks.

**Comment by knipknap** [comment]
You are looking for connection.set_timeout().

**Comment by masontrep** [comment]
Hmm tried that both in a simple script, and in a .py script.  Exscript.protocols.Exception.TimeoutException: Timeout while waiting for response from device

Here is what I tried:


import hashlib
import Exscript

from Exscript.util.interact import read_login
from Exscript.protocols import SSH2

account = read_login()            
conn = SSH2()                       
conn.connect('10.15.130.67')     
conn.login(account)                 
conn.execute('enable')                  
conn.execute('copy tftp://10.15.132.12/AT-iMG2400-4.4.4 AT-iMG2400-4.4.4')

conn.set_timeout(600)

conn.execute('end')

conn.execute('show boot')
print conn.response

conn.execute('sh int status')
print conn.response

conn.ececute('write mem')

conn.send('exit\r')                 
conn.close()                       

Any other thoughts?  Im still getting the same error about 30 to 40 seconds in.

Thanks!

**Comment by knipknap** [comment]
You have to set that *before* executing the long running command :-)

**Comment by masontrep** [comment]
head -> table -- Thank you that did it!
