### ISSUE TITLE
pypi tarball for 2.3.2

### ISSUE THREAD

**Issue by 1-61803** [knipknap/exscript#146]
Could you please fix the link?
As of now it's https://pypi.python.org/packages/2f/4a/1237da3cdc0766a3290e5195187d251af6e2c9f0453368cd730e545872cc/Exscript-2.3.2-py2.py3-none-any.whl

**Comment by knipknap** [comment]
Where do you see this link? We are not linking to Pypi anywhere.

**Comment by knipknap** [comment]
Do you mean the link *on* Pypi is broken? It's not a tarball, it's a wheel. That is intended.

**Comment by 1-61803** [comment]
Could you also add the complete source there?

**Comment by knipknap** [comment]
For a plain source download, I recommend using "git clone" or https://github.com/knipknap/exscript/archive/master.zip

**Comment by 1-61803** [comment]
Yeah, well, no, but thanks. I figured out a way in my ports system.
