### ISSUE TITLE
No module name resource

### ISSUE THREAD

**Issue by vikramrajsitpal** [knipknap/exscript#148]
Hello,
I was just using Exscript on windows 10 and turns out this issue is still there. Windows 7 did NOT throw any such error though. Can I please get an insight into this issue?
I could successfully install the module on Win10 but on running my first test, this issue popped up.
I am using Exscript 2.3.2, paramiko 2.2.1
`from Exscript.protocols import Telnet, Exception File "C:\Python27\lib\site-packages\Exscript\__init__.py", line 34, in <module> from Exscript.Queue import Queue File "C:\Python27\lib\site-packages\Exscript\Queue.py", line 40, in <module> from Exscript.util.decorator import get_label File "C:\Python27\lib\site-packages\Exscript\util\decorator.py", line 28, in <module> from Exscript.protocols.Exception import LoginFailure File "C:\Python27\lib\site-packages\Exscript\protocols\__init__.py", line 28, in <module> from Exscript.protocols.SSH2 import SSH2 File "C:\Python27\lib\site-packages\Exscript\protocols\SSH2.py", line 34, in <module> from paramiko.resource import ResourceManager ImportError: No module named resource`

**Comment by knipknap** [comment]
Thanks for the report! For a solution please see #145

**Comment by vikramrajsitpal** [comment]
Thanks @knipknap
