### ISSUE TITLE
replace pycrypto with pycryptodome

### ISSUE THREAD

**Issue by kewalaka** [knipknap/exscript#154]
I understand pycrypto is no longer developed, and it doesn't easily install on Windows without build tools (even so, getting errors).  Apparently, pycryptodome is actively developed and is a drop in replacement, this installs easily with pip/wheel, can this be used instead?

**Comment by knipknap** [comment]
Thanks for the heads up! I have pushed a fix.

**Comment by zmpeterson86** [comment]
I installed pycryptodome but it actually does not seem to replace everything in pycrypto
