### ISSUE TITLE
Configurable timeouts?

### ISSUE THREAD

**Issue by lathspell** [knipknap/exscript#163]
The http://exscript.readthedocs.io/en/latest/templates.html does not tell how to adjust the command timeout inside a template. It's sometimes needed for very long running commands.

**Comment by lathspell** [comment]
After seeing that the broken "functions" link points to the stdlib package, I assume this can be done using set_timeout(int) from http://exscript.readthedocs.io/en/latest/Exscript.stdlib.connection.html.

**Comment by knipknap** [comment]
Thanks, I fixed the link.
