### ISSUE TITLE
Driver file for Adtran DSLAMs [patch]

### ISSUE THREAD

**Issue by lathspell** [knipknap/exscript#168]
I've written a driver for Adtran DSLAMs so that I they will enter enabled mode automatically.

When connecting with "ssh -v" I only get the following so I assume that there is not much
chance for implementing check_*_for_os() methods, right?
```
debug1: Enabling compatibility mode for protocol 2.0
debug1: Local version string SSH-2.0-OpenSSH_7.4p1 Debian-10+deb9u3
debug1: Remote protocol version 2.0, remote software version OpenSSH_7.3
debug1: match: OpenSSH_7.3 pat OpenSSH* compat 0x04000000
debug1: Authenticating to d7-f155-2:22 as 'root'
...
debug1: Next authentication method: keyboard-interactive
Password: 
```

I called init_terminal() as part of the authorization() function. I had assumed that it gets called automatically on every login but it's apparently not the case?

```
# cat adtran.py
"""
A driver for the Adtran DSLAMs.
"""
from __future__ import absolute_import
from .driver import Driver

class AdtranDriver(Driver):

    def __init__(self):
        Driver.__init__(self, 'adtran')

    def init_terminal(self, conn):
        conn.execute('terminal length 0')
        conn.execute('terminal column 0')

    def auto_authorize(self, conn, account, flush, bailout):
        self.init_terminal(conn)
        conn.send('enable\r\n')
        conn.app_authorize(account, flush, bailout)
```

**Comment by knipknap** [comment]
You are correct, the SSH client info is rather unhelpful in this case; unfortunately most vendors don't customize it. In such cases, one can only hope for a more useful string being included in the device response after logging in.

init_terminal() is not called automatically; it's only called by Protocol.autoinit(), which is not invoked anywhere.

**Comment by knipknap** [comment]
In order to add this as a new driver, we would also need a test in

tests/Exscript/protocols/banners/

to make sure that there aren't any collisions with other drivers. In addition, the driver needs to be registered in __init__.py to make sure that it's used.

Could you send a pull request for that?
