### ISSUE TITLE
Display device prompt

### ISSUE THREAD

**Issue by champidead** [knipknap/exscript#171]
Hello,

Is there a way to display the device prompt?
This issue is related to issues #111 and #131.

Simply, I'd like to have this output:

```
<DEVICE>mmi-mode enable
Warning: Entered machine-to-machine mode. All the commands will be executed without being confirmed. Exercise caution when using this command. 
<DEVICE>system-view
[DEVICE]#
[DEVICE]interface Ethernet 0/0/1
[DEVICE-Ethernet0/0/1] clear configuration this
Warning[0x40530090]: All configurations of the interface will be cleared, and its state will be shutdown. Continue? [Y/N] :
Running...
Info[0x40530093]: Total 6 command(s) executed, 6 successful, 0 failed.
```

Instead of:

```
mmi-mode enable
Warning: Entered machine-to-machine mode. All the commands will be executed without being confirmed. Exercise caution when using this command. 
system-view
#
interface Ethernet 0/0/1
 clear configuration this
Warning[0x40530090]: All configurations of the interface will be cleared, and its state will be shutdown. Continue? [Y/N] :
Running...
Info[0x40530093]: Total 6 command(s) executed, 6 successful, 0 failed.
```

Yes, there are reasons I need this data:

- It helps to debug.
- Having the prompt is more convenient and readable.

Why not provide this feature as an option (e.g., a parameter).

Thanks for your work, Exscript is a nice toolbox.

**Comment by lathspell** [comment]
Do you use "--use-driver" or a custom python script? Without a special driver and using templates, I always see the prompt like:

```
d7-f155-1> show ip arp dynamic-arp-inspection
Bridgeport        Operstate         Vlancontrol       
   ...
```

**Comment by champidead** [comment]
Any update?

**Comment by knipknap** [comment]
I don't see any code where that should happen with Exscript. Are you sure that it's not stripped in your code? Do you have a simple test case where this happens?

**Comment by champidead** [comment]
Hello @knipknap, thanks for your interest in the issue.
Here is the simple test case:

```python
$ cat simple.py 

#!/opt/python3.6/bin/python3.6
from Exscript.util.interact import read_login
from Exscript.protocols import SSH2

# Login
account = read_login()
conn = SSH2()
conn.connect('DEVICE')
conn.login(account)

# Commands
conn.execute('display current-configuration interface ethernet 0/0/2')
print(conn.response)

# Logout
conn.send('exit\r')
conn.close()
```

Here is the output:

```
$ ./simple.py 
Please enter your user name [champi]: 
Please enter your password: 
display current-configuration interface ethernet 0/0/2
#
interface Ethernet0/0/2
 description Uplink
 shutdown
#
return
```

As you can see, the device prompt is missing.
I was expecting `<DEVICE>display current-configuration interface ethernet 0/0/2`.
For reminder, I'm using the [Huawei driver](https://github.com/knipknap/exscript/blob/master/Exscript/protocols/drivers/vrp.py).

**Comment by knipknap** [comment]
Ah! You are only printing conn.response, which by default does not include the prompt. If you want to print everything, you should be using the stdout argument of the protocol adapter instead. For more info, please see

https://exscript.readthedocs.io/en/latest/Exscript.protocols.protocol.html#Exscript.protocols.protocol.Protocol

Alternatively, if you want to make decisions based on the prompt, you can use the return value of execute(). The API documentation is here:

https://exscript.readthedocs.io/en/latest/Exscript.protocols.protocol.html#Exscript.protocols.protocol.Protocol.execute

**Comment by champidead** [comment]
Here is what I tried:

```python
#!/opt/python3.6/bin/python3.6
from Exscript.util.interact import read_login
from Exscript.protocols import SSH2
import sys # >>>>>>>>>> ADDED THIS <<<<<<<<<<

# Login
account = read_login()
conn = SSH2(stdout=sys.stdout) # >>>>>>>>>> ADDED THIS <<<<<<<<<<
conn.connect('DEVICE)
conn.login(account)

# Commands
conn.execute('display current-configuration interface ethernet 0/0/2')

# Logout
conn.send('exit\r')
conn.close()
```

Now I got the prompt:

```
$ ./simple.py 
Please enter your user name [dufour]: 
Please enter your password: 
<DEVICE>display current-configuration interface ethernet 0/0/2
#
interface Ethernet0/0/2
 description Uplink
 shutdown
#
return
```

Is this the recommended way to go?
Thanks!

**Comment by champidead** [comment]
Here is what I tried:

```python
#!/opt/python3.6/bin/python3.6
from Exscript.util.interact import read_login
from Exscript.protocols import SSH2
import sys # >>>>>>>>>> ADDED THIS <<<<<<<<<<

# Login
account = read_login()
conn = SSH2(stdout=sys.stdout) # >>>>>>>>>> ADDED THIS <<<<<<<<<<
conn.connect('DEVICE)
conn.login(account)

# Commands
conn.execute('display current-configuration interface ethernet 0/0/2')

# Logout
conn.send('exit\r')
conn.close()
```

Now I got the prompt:

```
$ ./simple.py 
Please enter your user name [champi]: 
Please enter your password: 
<DEVICE>display current-configuration interface ethernet 0/0/2
#
interface Ethernet0/0/2
 description Uplink
 shutdown
#
return
```

Is this the recommended way to go?
Thanks!

**Comment by knipknap** [comment]
Exactly :-)
