### ISSUE TITLE
SSH2 re-connection between authentication hook improvement

### ISSUE THREAD

**Issue by maximumG** [knipknap/exscript#187]
I submitted a change on how to handle the SSH2 reconnection hook. After my pull request, this hook was handled at driver level.

I think we can improve this feature by checking if the paramiko Transport object is currently active or not. In the case paramiko received a MSG_DISCONNECT from the remote server, the *active* attribute of the paramiko Transport object is set to *False*

It would be possible to improve the following line of code.

https://github.com/knipknap/exscript/blob/0d72fe22809c74c82dd8d9376ae145e8cd354b3e/Exscript/protocols/ssh2.py#L297

```python
if self.get_driver().reconnect_between_auth_methods or not self.client.active:
                self.close(force=True)
                self.client = self._paramiko_connect()
```

By doing this way we can detect if the SSH2 Transport channel as been cut between each authentication mechanism and reconnect automatically.

**Comment by knipknap** [comment]
Makes sense. Thanks for the pull request, it is merged.
