### ISSUE TITLE
connection.close() take long time. debug does not help

### ISSUE THREAD

**Issue by fpuleio** [knipknap/exscript#189]
hi,
any time i am running exscript, closign the current connection takes a long long time. around 10-15 seconds.
is this expected? is there any way to avoid such delay?

sample script is very easy:

>>>from Exscript.protocols import Telnet
>>>from Exscript import Account
...
>>> account = Account(credentials['username'], credentials['password'], credentials['enable'])
>>> conn = Telnet()  # We choose to use Telnet
>>> conn.set_driver('ios_xr')
>>> 
>>> conn.connect('x.x.x.x')
True
>>> conn.login(account)
>>> conn.close()
>>> 

running
:~$ python
Python 2.7.12 (default, Dec  4 2017, 14:50:18) 
[GCC 5.4.0 20160609] on linux2

following pip list:
Package       Version
------------- -------
asn1crypto    0.24.0 
bcrypt        3.1.4  
cffi          1.11.5 
configparser  3.5.0  
cryptography  2.3.1  
enum34        1.1.6  
et-xmlfile    1.0.1  
Exscript      2.5.7  
future        0.16.0 
idna          2.7    
ipaddress     1.0.22 
jdcal         1.4    
openpyxl      2.5.9  
paramiko      2.4.1  
pip           10.0.1 
ply           3.11   
pyasn1        0.4.4  
pycparser     2.18   
pycryptodomex 3.6.6  
PyNaCl        1.2.1  
pysmi         0.3.1  
pysnmp        4.4.6  
setuptools    39.1.0 
six           1.11.0 
wheel         0.31.1

**Comment by knipknap** [comment]
The clean way is:

```
> > > conn.login(account)
> > > conn.send('exit\r')
> > > conn.close()
```
The ugly, wrong way is:

```
> > > conn.login(account)
> > > conn.close(True)
```

**Comment by fpuleio** [comment]
used the clean way, much better now!
thanks knipknap
