### ISSUE TITLE
Publish version on PyPi

### ISSUE THREAD

**Issue by maximumG** [knipknap/exscript#193]
Hello,

Would it be possible to release a new version (2.6.3) of the library on PyPi ? I am not able to connect to Huawei devices until the commit eb77f5a57500c0c7e3673c4724d5b2cec58f3968. This commit is not part of any official release for now.

Thus, I need to install the DEVELOPMENT version directly from Github instead of an official release on PyPi.

Thanks.

**Comment by knipknap** [comment]
I currently have no access to a development machine; however, I would grant you the rights wo publish a new wheel, if you tell me your account name on PyPi. Creating a new release is as easy as

```
git tag -a v2.6.3 v2.6.3
git push --tags
make wheel
make dist-publish
```

**Comment by maximumG** [comment]
Thanks for your reply - really appreciate. My account name on PyPI is **maximumG**

**Comment by knipknap** [comment]
I'm getting an error:

User 'maximumG' does not have a verified primary email address and cannot be added as a Maintainer for project.

**Comment by maximumG** [comment]
> User 'maximumG' does not have a verified primary email address and cannot be added as a Maintainer for project.

It should be ok now.

**Comment by knipknap** [comment]
It worked! You should now have permissions to upload new releases, and to push changes to the main repository.

**Comment by maximumG** [comment]
Thanks for you work. I just uploaded a new version 2.6.3 on PyPi https://pypi.org/project/Exscript/2.6.3/

**Comment by knipknap** [comment]
Great, Thanks!

**Comment by JohnHay** [comment]
Could we have 2.6.3 added to the releases page too?

[https://github.com/knipknap/exscript/releases](url)
