### ISSUE TITLE
SigIntWatcher.child is tested but may not exists

### ISSUE THREAD

**Issue by Alex131089** [knipknap/exscript#199]
Hello, 

In `SigIntWatcher`, the `init` function is testing `self.child` (https://github.com/knipknap/exscript/blob/v2.6/Exscript/util/sigint.py#L62), but it may not exists, so the call ends with:
```
Traceback (most recent call last):
  File "...\Scripts\exscript", line 585, in <module>
    SigIntWatcher()
  File "...\site-packages\Exscript\util\sigint.py", line 62, in __init__
    if self.child == 0:
AttributeError: 'SigIntWatcher' object has no attribute 'child'
```

I guess a default value should be initialized, or set in the except clauses.

**Comment by knipknap** [comment]
Fixed in master, see above.
