### ISSUE TITLE
version in releases called DEVELOPMENT

### ISSUE THREAD

**Issue by JohnHay** [knipknap/exscript#202]
I'm trying to build a FreeBSD package of exscript v2.6 and have most of it working, but I am left with a warning:

> ===>  Configuring for py36-exscript-2.6
> /usr/local/lib/python3.6/site-packages/setuptools/dist.py:481: UserWarning: The version specified ('DEVELOPMENT') is an invalid version, this may not work as expected with newer versions of setuptools, pip, and PyPI. Please see PEP 440 for more details.
>   "details." % self.metadata.version
> 

I can see that exscript-2.6/Exscript/version.py have the version set to DEVELOPMENT.

Is that something that should be set somehow by me or should it be set before creating the release tar file?

**Comment by knipknap** [comment]
I would recommend using "make dist" to prepare the build. Alternativverlust, you could call ./version.sh directly.

**Comment by JohnHay** [comment]
> I would recommend using "make dist" to prepare the build. Alternatively, you could call ./version.sh directly.

Shouldn't that be done before tagging a new release? I'm not trying to build a package from master, but from a release tar.gz file. Other modules normally have that already set in the tar file. 

Attached is the Makefile needed to create a FreeBSD port/package of exscript. Once it is accepted by FreeBSD, exscript packages for all its releases will automatically be built. All the other dependencies are already port/packages.

[Makefile.txt](https://github.com/knipknap/exscript/files/3490362/Makefile.txt)

**Comment by knipknap** [comment]
Unfortunately the version number is not stored in the file, and therefore not in the snapshot. One alternative I can think of is pulling the release from PyPI, where the number is already included.

**Comment by JohnHay** [comment]
I found a way around it by adding a piece to the port Makefile that will replace the version in the two files and the port has now been accepted by FreeBSD, so I guess this can be closed.

```
post-patch:
	@${REINPLACE_CMD} -e \
		"{s#__version__ = '[^']*'#__version__ = '${PORTVERSION}'#;}" \
		${BUILD_WRKSRC}/VERSION.in ${BUILD_WRKSRC}/Exscript/version.py
```
