### ISSUE TITLE
print status(logger) and summarize(logger) syntax error

### ISSUE THREAD

**Issue by asoltes** [knipknap/exscript#205]
#SCRIPT
#!/usr/bin/env python
from Exscript import Queue, Logger
from Exscript.util.log import log_to
from Exscript.util.decorator import autologin
from Exscript.util.file import get_hosts_from_file, get_accounts_from_file
from Exscript.util.report import status, summarize

logger = Logger()  # Logs everything to memory.

@log_to(logger)
@autologin()
def do_something(job, host, conn):
    conn.execute('term len 0')
    conn.execute('show ip int brie')
    return job

accounts = get_accounts_from_file('accounts.cfg')
hosts = get_hosts_from_file('hostlist.txt',default_protocol='ssh2')

queue = Queue(verbose=5, max_threads=5)
queue.add_account(accounts)   
queue.run(hosts, do_something) 
queue.shutdown()       
#when i comment out the print status and summarize logger and be able to run a script
but unable to make an output of the command from my cisco device
#Print a short report.
#print status(logger)
#print summarize(logger)

++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
OUTPUT:
[root@dev-srv project]# python3 simple_conn.py 
All jobs enqueued.
Waiting for the queue to finish.   
172.16.0.10 succeeded.                         
172.16.0.10 job is done.                        
172.16.0.11 succeeded.                          
172.16.0.11 job is done.             
Shutting down queue...               
Queue shut down.
[root@dev-srv project]# 

+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
#uable to run a report because of incvalid syntax error
#Print a short report.
print status(logger)
print summarize(logger)

[root@dev-srv project]# python3 simple_conn.py 
  File "simple_conn.py", line 32
    print status(logger)
               ^
SyntaxError: invalid syntax
[root@dev-srv project]#

**Comment by Boehrsi** [comment]
With the following syntax it should work:

```
print (status(logger))
print (summarize(logger))
```
