### ISSUE TITLE
time out 

### ISSUE THREAD

**Issue by webpioneer** [knipknap/exscript#3]
hello Samuel ,

Thank you this great module that make our life easier .

Exscript.protocols.Exception.TimeoutException: Timeout while waiting for response from device
i get this exception above when i am running a command (show version ) on a cisco device that generates long output ,i thought about changing the timeout attribute , like this :
conn=SSH2(timeout=120)
but still i get the same error .
Is it better to change the buffer ? and how to achieve that .
this is my code :

from Exscript.util.interact import read_login
from Exscript.protocols import SSH2
import sys

USAGE='Usage : ./script hostname'

if len(sys.argv)==2:
    hostname=sys.argv[1]
else:
    print USAGE
    sys.exit(1)

commands=['show flash',
        'show version',]

account = read_login()     # Prompt the user for his name and password
conn = SSH2()              # We choose to use SSH2
# conn.buffer='1024'

conn.connect(hostname)  # Open the SSH connection
conn.login(account)        # Authenticate on the remote host
print 'you are logged in'
for cmd in commands:
    conn.execute(cmd)   # Execute command
    print conn.response

conn.send('exit\r')  
print 'closing'      # Send the "exit" command
conn.close()                 # Wait for the connection to close

**Comment by singhujjwal** [comment]
Thanks @webpioneer 
conn.execute('term len 0')
conn.execute('term width 0')

worked for me.

Thanks
