### ISSUE TITLE
Need assistance on get_hosts_from_file & get_accounts_from_file

### ISSUE THREAD

**Issue by deleonstrong** [knipknap/exscript#42]
What I am trying to do is to simply import a hosts & accounts file from the script and perform the operation to gather information.  I have this working fine when I add acount information in manually.  I need help with the specific format of the two files and then I was wandering How I can verify the list using the interpreter.

MY WORKING SCRIPT HAS

account1 = Account('user1', 'password1')
host1    = Host('ssh://1.1.1.1')
host1.set_account(account1)

account2 = Account('user2', 'password2')
host2    = Host('ssh://2.2.2.2')
host2.set_account(account2)

def do_something(job, host, conn):
    conn.execute('show version')

start([account1 , account2], [host1 , host2], do_something, max_threads = 2)

**

When I use the above it works fine.  Now I want to use accounts.cfg & myhosts.txt to import the users and hosts address'.  I need to know what the exact format for accounts and hosts files are supposed to be.

**

SCRIPT TO I WANT TO TRY

from Exscript.util.start import start
from Exscript.util.file import get_hosts_from_file
from Exscript.util.file import get_accounts_from_file
from Exscript import Host, Account
import datetime
# read input data

accounts = get_accounts_from_file('accounts.cfg')
hosts = get_hosts_from_file('myhosts.txt')

def do_something(job, host, conn):
    conn.execute('show version')

start(accounts, hosts, do_something, max_threads = 2)

**

My 'accounts.cfg' looks like this

[account-pool]
user1 = password1==
user2 = password2==

What does the 'myhosts.txt' for host1    = Host('ssh://1.1.1.1')
and host2    = Host('ssh://2.2.2.2')?

If I want to print the list to see if the information is imported correctly, how would I do that?

> > > from Exscript.util.start import start
> > > from Exscript.util.file import get_hosts_from_file
> > > from Exscript.util.file import get_accounts_from_file
> > > from Exscript import Host, Account
> > > accounts = get_accounts_from_file('accounts.cfg')
> > > print type(accounts)
> > > <type 'list'>
> > > print accounts
> > > [<Exscript.Account.Account object at 0x10ef56510>]

Thanks for the help

T.

**Comment by ccasabigs** [comment]
hi 
the only don't work for mi is from Exscript.util.file import get_accounts_from_file
Everything else works great, 
thanks for the help

this is the error message

python pytokill-test.py 
Traceback (most recent call last):
  File "pytokill-test.py", line 31, in <module>
    conn.login(accounts)
  File "/home/gxpy/.local/lib/python2.7/site-packages/Exscript/protocols/Protocol.py", line 633, in login
    with self._get_account(account) as account:
  File "/home/gxpy/.local/lib/python2.7/site-packages/Exscript/protocols/Protocol.py", line 609, in _get_account
    account.__enter__()
AttributeError: 'list' object has no attribute '__enter__'

**Comment by knipknap** [comment]
You can not pass multiple accounts to login().

**Comment by ccasabigs** [comment]
But I only have one account, in the file and I need to use the encryption
my code for authenticate

accounts = get_accounts_from_file('accounts.cfg')
#print accounts
conn = SSH2()                   
conn.connect(var3)   
## Authenticate
#conn.authenticate(accounts)        	
conn.login(accounts)
#conn.app_authorize(accounts)

For the 3 methods above gives me the same error,
please help

**Comment by ccasabigs** [comment]
hi
Thank you for your comment really helped me. I managed to make it work with this line 

for accounts in get_accounts_from_file('accounts.cfg'):
Thanks
