### ISSUE TITLE
Suppressing Exscript logs

### ISSUE THREAD

**Issue by coxley** [knipknap/exscript#66]
What would be the easiest way to supress/disable the Exscript logger?

Sometimes when I'm doing custom logging, my logger will get filled with logs from Exscript. Is there a way to suppress that?

**Comment by knipknap** [comment]
Is this still an (Exscript-caused) issue? Looking at the above, I would assume there's nothing Exscript is doing wrong or could do better to solve the problem.

**Comment by coxley** [comment]
Nah this could be fixed by `logging.getLogger(exscripts_log_handle).setLevel(logging.CRITICAL)`. Apparently I didn't know better. :)

**Comment by knipknap** [comment]
Great, Thank you :-)
