### ISSUE TITLE
"timeout expired" error on Cisco routers when trying to provide enable password 

### ISSUE THREAD

**Issue by maxbsd** [knipknap/exscript#67]
After the latest commit "Merge pull request #64 from knipknap/feature/manual_driver setting driver manually" I am unable to login to any Cisco router:

enable
Password: 
% Password:  timeout expired!
% Error in authentication.

**Comment by egroeper** [comment]
So it was running fine on commit 1af983e188879b5b78231821b839162a8dbca9cb?
If not, can you give me the last commit / version on which it was running?

**Comment by maxbsd** [comment]
Yep, the last successful run was on 1af983e188879b5b78231821b839162a8dbca9cb. Thank you.

**Comment by egroeper** [comment]
Sorry. I really don't see a way how my changes could cause this.
Have you tried going back to 1af983e? It is working again then?

To me it seems like there has happened something else causing your issues.
I mean: You don't use the new feature of setting the driver, do you? You just updated the code?

Can you give me a code snippet and/or raise verbosity level when running this?

Unfortunately I don't have access to any cisco devices.

**Comment by maxbsd** [comment]
1af983e is currently working fine for me.

Yes, I pulled your new code but my code is the same as before, here it is:
`account = Exscript.Account('admin', password='123456', password2='654321')
 conn = Exscript.protocols.SSH2(driver=driver_map['ios'])
 for i in range(3):
     try:
         conn.set_timeout(45)
         res = conn.connect('10.20.5.111')
         time.sleep(0.1)
     except Exception as e:
         ...
    else:
        conn.login(account)
        conn.execute('terminal length 0')`

Please tell me if the code above seems okay to you or not and if it's okay I will raise the verbosity level and run it again for getting more informative logs. Thank you.

**Comment by egroeper** [comment]
Thanks for your example. I now see the problem. I'm working on a fix.
