### ISSUE TITLE
Manually set exscript timeout after establishing a connection

### ISSUE THREAD

**Issue by mpenning** [knipknap/exscript#70]
I'm trying to figure out whether you can manually specify a timeout before an exscript conn.execute()... The online docs seem to indicate that this should be possible, but this bombs with an error when I try it...

    import sys

    from Exscript.util.interact import read_login
    from Exscript.protocols import SSH2
    from Exscript.protocols.drivers import ios, shell, generic

    account = read_login()
    conn = SSH2(debug=0, auto_verify=False, stdout=sys.stdout, timeout=15)
    conn.buffer = 2048
    conn.set_driver('ios')
    conn.connect('172.16.1.1')
    conn.login(account)
    conn.execute('term pager 0')
    conn.set_timeout(5)     ### <------ Required functionality here
    conn.execute('show ver')

When I run that script, I get this error while running the `conn.set_timeout(5)` line:
    AttributeError: 'int' object has no attribute 'tail'

Is this a bug, or is this even supposed to be supported?

**Comment by egroeper** [comment]
Which version of exscript are you using?
```auto_verify``` was removed from protocol specific options in commit b609a31609e1.
Please try again with current master.

**Comment by egroeper** [comment]
Please reopen, if you have further information and/or it doesn't work with current master.
