### ISSUE TITLE
Issues with a log files

### ISSUE THREAD

**Issue by evakulen** [knipknap/exscript#74]
Don't have to much experience with Python, so apologize if asking the silly question.

My code:
```python
    log = open('log.txt','w+')
    logError = open('errors-log.txt','w+')
    start(accounts,hosts,do_commands,stdout=log,stderr=logError,max_threads = 1)
```
I have 2 questions about a log files:

1. When using a code mentioned above only one log file is being created (which is obvious, since i'm writing output into one file), however I'm not able to understand how to make a file per device.
2. If I put "max_threads = 2" I'm getting a log file filled with text below instead of real log of command execution.
 
>> In progress: [192.168.255.128] 0/2 (0%)                                       In progress: [192.168.255.128|192.168.255.128] 0/2 (0%)                                                       192.168.255.128 succeeded.
In progress: [192.168.255.128|192.168.255.128] 1/2 (50%)                                                        192.168.255.128 succeeded.
In progress: [192.168.255.128] 2/2 (100%)                                         

Can you please suggest something?
Thank you.

**Comment by renard** [comment]
try to add `verbose=0` to the `start` command, it works for `run`.

**Comment by egroeper** [comment]
The convenience method "run" uses Queue (see Queue.py) in the background.
Having a look at the [Queue documentation](http://knipknap.github.io/exscript/api/Exscript.Queue-class.html#__init__) you can see which output is written where depending on the verbosity level.
Currently you can't get the "live conversation" when you use threading.

The question is: What do you want to achieve and why?
When testing you could simply set `max_threads` to 1 and have a look at the live conversation.
After testing it shouldn't be necessary to see the conversation.
You should add status output / debugging messages directly to your code (in do_command) instead.

**Comment by evakulen** [comment]
The idea was to have a script which can login to the big number of network devices (1000+), issue some "show" commands there and write output into the file. 
It's possible to make it with 1 thread, but I just wanted to make it faster. Though now I realize the challenge which my idea creates.
I just wanted to check if you had any similar ideas. Will think on it by myself in a meantime.

**Comment by egroeper** [comment]
This should be no problem at all, but "misusing" exscripts logging feature for that poses a problem.
Simply open a "logfile" for each host in your "do_commands" method (which is called once for each host).
Then write the responses to your show commands to that file and close it at the end of the method.

You don't have a problem using threads, if you do it that way. Especially if the filename depends on the host and the host is unique.

**Comment by renard** [comment]
@evakulen I wrote that piece of software. Please have a look at https://github.com/renard/cidr.

Let me know if you need some updates.

**Comment by evakulen** [comment]
Thanks for clarification!
