### ISSUE TITLE
API tutorial 

### ISSUE THREAD

**Issue by ash27win** [knipknap/exscript#75]
Hi,

I was checking a program python API tutorial,

from Exscript.util.interact import read_login
from Exscript.protocols import SSH2

account = read_login() # Prompt the user for his name and password
conn = SSH2() # We choose to use SSH2
conn.connect('localhost') # Open the SSH connection
conn.login(account) # Authenticate on the remote host
conn.execute('uname -a') # Execute the "uname -a" command
conn.send('exit\r') # Send the "exit" command
conn.close() # Wait for the connection to close

I made a python file test.py .Then i tried executing with the commands python test.py and python test.py ssh://localhost in both cases the script ran and asked for username and password ,when i entered the credentials .It returned back to shell prompt without executing uname-a command.Any recommendations would be highly appreciated.

**Comment by mpenning** [comment]
The following runs without issue for me... it's basically a cut and paste from your code above, but I added explicit imports

    from Exscript.util.interact import read_login
    from Exscript.protocols import SSH2, Telnet

    account = read_login()
    conn = SSH2() 
    conn.connect('localhost') 
    conn.login(account)
    conn.execute('uname -a')   # Execute the "uname -a" command
    print conn.response   # <------ you have to get the response from the uname command if you want it
    conn.send('exit\r')
    conn.close()

I'm running Python 2.7.3, Exscript 2.1.440, paramiko 1.15.2.

It also wouldn't hurt to explicitly declare the driver before you connect, but strictly speaking this shouldn't be required for the example above.

    conn.set_driver('shell')

**Comment by egroeper** [comment]
@mpenning is right. Usually you run execute and then analyze the `conn.response` (or print it).
Have a look at the [simple demo](https://github.com/knipknap/exscript/blob/master/demos/simple/simple.py).

If you found this code snippet anywhere in the exscript docs, please reopen this bug and give me a hint where to search for it, so I can fix the docs.

**Comment by ash27win** [comment]
Thanks #mpenning,It worked.
