### ISSUE TITLE
aironet driver issue

### ISSUE THREAD

**Issue by maximumG** [knipknap/exscript#77]
Hello,

I was more than please to see that a new driver was released for Cisco WLC running aironet OS.
**Unfortunately the prompt regex is not working on Cisco WISM2 card.**

The prompt of a WISM2 card is as follow:

```bash
User: <username>
Password:<password>
(WiSM-slot2-1) >
```
The actual regex for **_prompt_re** is not mathcing this case. I suggest to change the driver to such regex

```python
_prompt_re   = [re.compile(r'([\r\n]\(.*?\)\s>$)')]
```

The **autoinit()** function is also bogus on my side. The command to send on WISM2 card is

```bash
(WiSM-slot2-1) >config paging disable
```

**Comment by mpenning** [comment]
Hello and thank you for reporting this issue.

I did not consider WiSM when I wrote the driver; however, the paging issue is a bug.  I'm commiting code to fix both issues, but I'm not sure when it will be sync'd to master or posted on pypi.

**Comment by mpenning** [comment]
To evaluate the changes, please see this branch in my fork...

https://github.com/mpenning/exscript/tree/iss77_aironet

The test suite passes

    ...................................................................................................................................................................
    ...............................................................................................................................
    ----------------------------------------------------------------------
    Ran 508 tests in 204.385s

    OK
    (py27_test)[mpenning@tsunami exscript]$

**Comment by maximumG** [comment]
Thanks its working as expected. I'm waiting for your fix to be integrated into the main Exscript project.

**Comment by egroeper** [comment]
@job Could you please update the pypi entry? We probably should think about how and when we make new releases (release tagging and such).

**Comment by job** [comment]
@egroeper done

**Comment by egroeper** [comment]
@job Thanks :-)
