### ISSUE TITLE
Make use of paramikos new banner timeout

### ISSUE THREAD

**Issue by egroeper** [knipknap/exscript#80]
Perhaps we should make use of paramikos new [banner timeout option](https://github.com/paramiko/paramiko/pull/362). We could set the value to connect_timeout or add a new parameter.
I currently prefer the first option.
Since network devices are rebooted rarely the has no high priority. It would only take effect, if the ssh daemon already accepts TCP connections, but doesn't present banner, yet.

**Comment by knipknap** [comment]
Done.
