### ISSUE TITLE
API tutorial - start versus quickstart

### ISSUE THREAD

**Issue by dlin28690** [knipknap/exscript#95]
In the examples from sections "Running a script on multiple hosts" and "Loading hosts from a text file" start is called with two required arguments and kwargs.  The method actually requires three required arguments and can accept kwargs.  I think the example intends usage of quickstart instead of start.

start(hosts, do_something, max_threads = 2)

**Comment by egroeper** [comment]
Thanks for your hint. As mentioned in the text the example should use quickstart. I fixed it.
