### ISSUE TITLE
enterasys driver: paging doesn't get disabled

### ISSUE THREAD

**Issue by egroeper** [knipknap/exscript#97]
Currently the driver does not disable paging.

"set length 0" could be used. Does this work everywhere?

**Comment by knipknap** [comment]
Hi Enno, is this for enterasys.py, or enterasys_wc.py? Since there has not been any activity for a long time, I would just add it now.

**Comment by knipknap** [comment]
Closing for now. Feel free to re-open if anyone can provide more info.
