### ISSUE TITLE
SSH Tunnel

### ISSUE THREAD

**Issue by Ka0sFact0r** [knipknap/exscript#99]
I am fairly new to Python but I have found Exscript very useful with one exception. To reach many devices on my company's network I need to create an ssh tunnel through a jump server and then connect to the router from there. I have been digging through the code trying to find if there is a built in way to handle this. Is there built in functionality for this or am I out of luck using Exscript and need to switch to something else?

**Comment by egroeper** [comment]
I'm not aware of any solution using exscript besides running exscript / your scripts directly from the jump server.
exscript assumes you have network connectivity to the devices you want to connect to and, to my knowledge, doesn't implement any tunneling feature itself.
